//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joel_Gramajo_202008025_Lab_13_repaso_segundo_parcial_n1 {
    
    
    public partial class ViewSwitcher {
    }
}
